project:
  type: website
  output-dir: docs

website:
  title: "Dr Saufi"
  favicon: images/mylogo_white2.png
  navbar:
    title: false
    logo: images/mylogo_white.png
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - services.qmd
      - books.qmd
  page-footer: 
    background: light
    left: © 2024 Dr Muhammad Saufi Abdullah
    right: This website is built with [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank}, Quarto and [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/drsaufi){target=_blank}

format:
  html:
    theme: 
     - solar
     - styles.scss
    mainfont: Nunito
    toc: true
    page-layout: full

editor: visual

