---
title: "About"
toc: false
editor: visual
---

Medical Officer | Public Health | Epidemiology | Statistical Analysis | Public Speaking | Speaker & Author

## {{< fa user-doctor >}} Overview

Over 10 years of experience in the medical and health fields, currently a student in Doctor of Public Health (Epidemiology) program. Experienced in delivering talks and leading workshops on epidemiology, statistical analysis, and public health. Actively involved in consultations and simplifying complex health topics for broader audiences. Passionate about teaching, sharing knowledge, and making data-driven solutions accessible to all.

## {{< fa graduation-cap >}} Education

**Doctor of Public Health (Epidemiology) | 2023 - Ongoing**

- Department of Community Medicine
- School of Medical Sciences
- Universiti Sains Malaysia

**Master of Public Health (MPH) | 2023**

- Department of Community Medicine
- School of Medical Sciences
- Universiti Sains Malaysia

**Bachelor of Medicine and Surgery (MBBCh) | 2013**

- Kasr Al-Ainy Medical School
- Cairo University

## {{< fa briefcase >}} Experience

**Ministry of Health Malaysia**

- Medical Officer | October 2016 - Present
- House Officer | June 2014 - September 2016

## {{< fa book-open >}} Skills and Certifications

**Statistical Analysis and Software**

- R Software (RStudio and Quarto)
- Statistical Package for the Social Sciences (SPSS)

**Public Speaking, Communication, and Leadership**

- Speak to Breakthrough Masterclass 2024
- Speak to Lead Masterclass 2024
- Speak to Influence Masterclass 2024
- Influential Impact Masterclass 2023

**Microsoft Office Specialist: Associate (Office 365)**

- Microsoft Office Specialist: Excel Associate (Office 365)
- Microsoft Office Specialist: PowerPoint Associate (Office 365)
- Microsoft Office Specialist: Word Associate (Office 365)
